name: class-share
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - networkx
  - mojimoji
  - scipy
  - scikit-learn
  - pygraphviz
  - seaborn
  - pip:
    - mojimoji
